server:
  port: 3000 #服务端口

spring:
  redis:
    database: 1 #数据库索引
    host: localhost #服务器地址
    port: 6379 #端口
    password:  #密码，默认为空
    timeout: 1000 #超时时间，单位毫秒
    lettuce:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

  thymeleaf:
    cache: false #是否缓存，关闭缓存，否则刷新无法看到实时页面
    suffix: .html #后缀
    mode: HTML #类型
